"""
core/ingestion/cleaner_factory.py

CleanerFactory: constructs a Cleaner configured for a specific business type.

Business-type-specific boilerplate patterns are declared here.  They are
prepended to the default set inside Cleaner, so they take priority.

Why here and not in config JSON?
---------------------------------
Boilerplate patterns are regex objects — they are code, not data.  Putting
raw regex strings in JSON is fragile (escaping, readability, no syntax check).
The factory keeps patterns in Python where they are testable and type-checked.
If per-tenant customisation is ever needed, the factory can be extended to
accept additional pattern lists from a config section.

Business types covered
----------------------
    news        — news article footers, share/comment prompts, ad blocks
    policy      — document headers/footers, approval tables, revision history
    workflow    — system-generated step labels, status lines
    equipment   — parts table footers, standard disclaimers, QR code lines
    quality_kb  — standard document headers, revision tables
    generic     — no extra patterns (default Cleaner)
"""

from __future__ import annotations

import re

from core.ingestion.cleaner import Cleaner

# ---------------------------------------------------------------------------
# Per-business boilerplate pattern lists
# ---------------------------------------------------------------------------

_NEWS_PATTERNS: list[re.Pattern] = [
    # Social share prompts
    re.compile(r"^(?:分享|转发|评论|点赞|收藏)\s*[\d]*.*$", re.MULTILINE),
    # "N readers" / "N views"
    re.compile(r"^\d+\s*(?:人阅读|次阅读|次浏览|views?|reads?).*$",
               re.MULTILINE | re.IGNORECASE),
    # Editor / source attribution lines at article end
    re.compile(r"^(?:来源|编辑|责编|作者)[：:]\s*.{0,60}$", re.MULTILINE),
    # Ad / sponsored content markers
    re.compile(r"^(?:广告|AD|advertisement|sponsored).*$",
               re.MULTILINE | re.IGNORECASE),
    # "Related reading" block header
    re.compile(r"^相关(?:阅读|推荐|链接).*$", re.MULTILINE),
]

_POLICY_PATTERNS: list[re.Pattern] = [
    # Approval / signature table rows (common in Chinese gov/enterprise policy)
    re.compile(r"^(?:起草|审核|批准|会签)[人者单位部门]*[：:]\s*_{3,}.*$", re.MULTILINE),
    # Revision history table rows
    re.compile(r"^\d{4}[-./年]\d{1,2}[-./月]\d{1,2}[日]?\s+.{0,40}\s+\d+\.\d+.*$",
               re.MULTILINE),
    # "This document is controlled / 受控文件" stamp lines
    re.compile(r"^.*(?:受控文件|controlled\s+document|uncontrolled\s+copy).*$",
               re.MULTILINE | re.IGNORECASE),
    # Distribution list headers
    re.compile(r"^发(?:送|放)范围[：:].*$", re.MULTILINE),
]

_WORKFLOW_PATTERNS: list[re.Pattern] = [
    # System-generated node ID lines
    re.compile(r"^(?:节点|Node)\s*(?:ID|编号)[：:\s]+[\w\-]+.*$",
               re.MULTILINE | re.IGNORECASE),
    # Workflow engine status stamps
    re.compile(r"^(?:状态|Status)[：:\s]+(?:待处理|处理中|已完成|PENDING|IN_PROGRESS|DONE).*$",
               re.MULTILINE | re.IGNORECASE),
    # Timestamp-only lines generated by workflow systems
    re.compile(r"^\d{4}[-/]\d{2}[-/]\d{2}\s+\d{2}:\d{2}:\d{2}\s*$", re.MULTILINE),
]

_EQUIPMENT_PATTERNS: list[re.Pattern] = [
    # Parts-list table footer notes
    re.compile(r"^[\*※]\s*(?:以上数量|数量仅供|规格如有变动).*$", re.MULTILINE),
    # QR code / barcode label lines
    re.compile(r"^(?:二维码|QR\s*Code|条形码|Barcode)[：:\s].*$",
               re.MULTILINE | re.IGNORECASE),
    # Warranty / disclaimer boilerplate
    re.compile(r"^.*(?:本公司保留|we\s+reserve\s+the\s+right|all\s+specifications\s+subject).*$",
               re.MULTILINE | re.IGNORECASE),
]

_QUALITY_KB_PATTERNS: list[re.Pattern] = [
    # Standard document number header
    re.compile(r"^(?:标准编号|Standard\s+No\.?)[：:]\s*.{0,30}$",
               re.MULTILINE | re.IGNORECASE),
    # Normative reference section header (content indexed separately)
    re.compile(r"^规范性引用文件\s*$", re.MULTILINE),
    # "This page intentionally left blank" in quality docs
    re.compile(r"^(?:此页有意留空|this\s+page\s+intentionally\s+left\s+blank).*$",
               re.MULTILINE | re.IGNORECASE),
]

_BUSINESS_TYPE_PATTERNS: dict[str, list[re.Pattern]] = {
    "news":       _NEWS_PATTERNS,
    "policy":     _POLICY_PATTERNS,
    "workflow":   _WORKFLOW_PATTERNS,
    "equipment":  _EQUIPMENT_PATTERNS,
    "quality_kb": _QUALITY_KB_PATTERNS,
}


# ---------------------------------------------------------------------------
# Factory
# ---------------------------------------------------------------------------

class CleanerFactory:
    """
    Builds a Cleaner instance pre-loaded with boilerplate patterns
    for the given business type.

    Usage
    -----
        cleaner = CleanerFactory.for_business_type("policy")
        doc = cleaner.clean(doc_id="...", raw_text="...", business_type="policy")
    """

    @staticmethod
    def for_business_type(business_type: str) -> Cleaner:
        """
        Return a Cleaner configured for `business_type`.
        Falls back to a generic Cleaner (no extra patterns) for unknown types.
        """
        patterns = _BUSINESS_TYPE_PATTERNS.get(business_type, [])
        return Cleaner(extra_boilerplate_patterns=patterns)

    @staticmethod
    def generic() -> Cleaner:
        """Return a Cleaner with only the default rule set (no extra patterns)."""
        return Cleaner()

    @staticmethod
    def supported_business_types() -> list[str]:
        """List of business types with dedicated boilerplate patterns."""
        return list(_BUSINESS_TYPE_PATTERNS.keys())
