"""
core/ingestion/enhanced_document.py

Data transfer object for the output of the LLM enhancement stage.

EnhancedDocument wraps a CleanedDocument and adds:
  - Five optional derived fields (summary, keywords, entities,
    potential_questions, context_padding).
  - An `enhanced` flag that is True only when ALL requested fields
    were successfully generated by the LLM.
  - An `enhancement_error` field that records the failure reason when
    degradation_policy == "rules_only_and_flag" triggered.

Design rules
------------
- The authoritative `text` field is NEVER modified.  `mutate_source=False`
  is enforced here: EnhancedDocument.text is always identical to
  CleanedDocument.text.  Callers accessing .text always get the canonical text.
- Derived fields are Optional[str] / Optional[list[str]].  A None value means
  the field was either disabled in config or failed to generate.
- This DTO is what the Chunker (P1-06) and Embedder (P1-08) receive.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from core.ingestion.cleaning_record import CleanedDocument


@dataclass
class EnhancedDocument:
    """
    Output of the LLM enhancement stage.

    Attributes
    ----------
    cleaned:
        The upstream CleanedDocument.  Source of truth for doc_id,
        original_length, cleaning log, business_type, source_metadata.
    enhanced:
        True  → LLM enhancement ran and all requested fields succeeded.
        False → Enhancement was disabled OR LLM failed and
                degradation_policy == "rules_only_and_flag" applied.
    enhancement_error:
        Human-readable error message when enhanced=False due to LLM failure.
        None when enhanced=True or when enhancement was globally disabled.
    summary:
        A short (2–5 sentence) summary of the document text.
    keywords:
        List of key terms / phrases extracted from the text.
    entities:
        List of named entities (people, organizations, locations, codes).
    potential_questions:
        List of questions this document text could answer.
    context_padding:
        A short contextual blurb (1–2 sentences) that can be prepended to
        a chunk to give the embedding model document-level context.
        Typically: "This document is about X and discusses Y."
    """

    cleaned: CleanedDocument

    enhanced: bool = False
    enhancement_error: str | None = None

    summary: str | None = None
    keywords: list[str] | None = None
    entities: list[str] | None = None
    potential_questions: list[str] | None = None
    context_padding: str | None = None

    # ------------------------------------------------------------------
    # Convenience accessors — mirror CleanedDocument so callers need
    # only hold an EnhancedDocument reference
    # ------------------------------------------------------------------

    @property
    def doc_id(self) -> str:
        return self.cleaned.doc_id

    @property
    def text(self) -> str:
        """
        The authoritative canonical text.
        ALWAYS identical to CleanedDocument.text — mutate_source=False.
        """
        return self.cleaned.text

    @property
    def business_type(self) -> str:
        return self.cleaned.business_type

    @property
    def source_metadata(self) -> dict:
        return self.cleaned.source_metadata

    def summary_line(self) -> str:
        """One-line status for logging."""
        fields_generated = [
            f for f in ("summary", "keywords", "entities",
                        "potential_questions", "context_padding")
            if getattr(self, f) is not None
        ]
        return (
            f"doc_id={self.doc_id} "
            f"enhanced={self.enhanced} "
            f"fields={fields_generated}"
            + (f" error={self.enhancement_error!r}" if self.enhancement_error else "")
        )
